name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build Go project
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o easygo-${{ matrix.os }}-${{ matrix.arch }} .

      - name: Create archive
        run: |
          if [ "${{ matrix.os }}" == "windows" ]; then
            zip easygo-${{ matrix.os }}-${{ matrix.arch }}.zip easygo-${{ matrix.os }}-${{ matrix.arch }}
          else
            tar -czvf easygo-${{ matrix.os }}-${{ matrix.arch }}.tar.gz easygo-${{ matrix.os }}-${{ matrix.arch }}
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            easygo-${{ matrix.os }}-${{ matrix.arch }}.tar.gz
            easygo-${{ matrix.os }}-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.MY_CUSTOM_TOKEN }}
